<a href="https://colab.research.google.com/github/Ismael636/Proyectos-tareas-/blob/main/3jercicios%20clase%2009.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Modulo numpy

import numpy as nombre #es muy comun escribir np
a = [1,2,3]
print(type(a))
a = nombre.array(a)# hace el cambio a tipo vector
print(type(a))
print(3*a)
print(a+a)

<class 'list'>
<class 'numpy.ndarray'>
[3 6 9]
[2 4 6]


In [15]:
diez = nombre.linspace(1,10,10)
print(diez)

ceros = nombre.zeros(3)
print(ceros)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0. 0. 0.]


In [24]:
b = nombre.array([-1,-60,12,3.5,2,3,3])
Min = nombre.amin(b) # la funcion amin da el valor mas pequeño de un vector
print(Min)

Max = nombre.amax(b)#la funcion max da el valor mas grande
print(Max)

donde = nombre.where(b == 3.5)#indica en que posicion esta un valor del vector
print(donde)
donde2 = nombre.where(b==3)
print(donde2)

-60.0
12.0
(array([3]),)
(array([5, 6]),)


In [27]:
#x^2 - 3x + 2 = 0, ecuacion a resolver

ec1 = nombre.array([1,-3,2])#se utiliza como la chicharronera
solu1 = nombre.roots(ec1)
print(solu1)
print('\n')
#4x^4 - 2x^2 + 3x -2 = 0
ec2 = nombre.array([4,-2,3,-2])
solu2 = nombre.roots(ec2)
print(solu2)


[2. 1.]


[-0.05562363+0.90272122j -0.05562363-0.90272122j  0.61124726+0.j        ]


In [31]:
#5x - 3y -z = 1
#x + 4y -6z = -1
#2x + 3y + 4x = 9
X = nombre.array([[5,-3,-1],[1,4,-6],[2,3,4]])
val = nombre.array([1,-1,9])
print(X)
print(val)
print('\n')
solucion = nombre.linalg.solve(X,val)#resuelve un sistema de ecuaciones
print(solucion)

[[ 5 -3 -1]
 [ 1  4 -6]
 [ 2  3  4]]
[ 1 -1  9]


[1. 1. 1.]


In [33]:
y = nombre.array([[2,-6,-1],[9,3,-6],[7,3,7]])
#print(y)
XY = nombre.matmul(X,y)
print(XY)

[[-24 -42   6]
 [ -4 -12 -67]
 [ 59   9   8]]
